# Generated by Django 5.0.6 on 2025-04-19 04:48

import issuedbooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuedbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='due_date',
            field=models.DateField(default=issuedbooks.models.default_due_date),
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
