# Generated by Django 5.2 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('primary_school_name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('1st grade', '1st grade'), ('2nd grade', '2nd grade'), ('3rd grade', '3rd grade'), ('4th grade', '4th grade'), ('5th grade', '5th grade'), ('6th grade', '6th grade'), ('7th grade', '7th grade'), ('8th grade', '8th grade')], max_length=20)),
                ('stream', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('white', 'White')], max_length=20)),
            ],
        ),
    ]
